package com.github.fevernova.io.data.message;


/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
@org.apache.avro.specific.AvroGenerated
public enum Opt implements org.apache.avro.generic.GenericEnumSymbol<Opt> {
    INSERT, UPDATE, DELETE;

    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser()
            .parse("{\"type\":\"enum\",\"name\":\"Opt\",\"namespace\":\"com.github.fevernova.io.data.message\",\"symbols\":[\"INSERT\",\"UPDATE\","
                   + "\"DELETE\"]}");


    public static org.apache.avro.Schema getClassSchema() {

        return SCHEMA$;
    }


    public org.apache.avro.Schema getSchema() {

        return SCHEMA$;
    }
}
